torso_params: 
  length: 0.46
  width: 0.216
  height: 0.18
  mass: 36
  start_pos: [0, 0, 0.5]

head_params:
  length: 0.3
  width: 0.216
  height: 0.18
  mass: 18
  offset: [0.0254, 0, 0]  

thigh_params: 
  length: 0.18
  width: 0.08
  mass: 3.375
  torso_offset: [-0.108, 0.00, 0]
  head_offset: [0.027, 0.0, 0]

shin_params: 
  length: 0.216
  width: 0.08
  mass: 1.2
  offset: [0, 0.0, 0]

wheel_params:
  radius: 0.1
  width: 0.1
  mass: 2.25
  offset: [0, 0.00, 0]
  friction: [1, 0.005, 0.0001]
  solref: [0.2, 0.5]
