torso_params: 
  length: 0.25
  width: 0.15
  height: 0.1
  mass: 10
  start_pos: [0, 0, 0.5]

head_params:
  length: 0.25
  width: 0.15
  height: 0.1
  mass: 10
  offset: [0.05, 0, 0]

thigh_params: 
  length: 0.1
  width: 0.04
  mass: 0.5
  torso_offset: [-0.02, 0.00, 0]
  head_offset: [0.02, 0.0, 0]

shin_params: 
  length: 0.16
  width: 0.04
  mass: 0.5
  offset: [0, 0.0, 0]

wheel_params:
  radius: 0.065
  width: 0.07
  mass: 0.5
  offset: [0, 0.00, 0]
  friction: [1, 0.005, 0.0001]
  solref: [0.2, 0.5]

